import glob
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [('app', glob.glob('app/*.*')), ('config', glob.glob('config/*.*')), ('data', glob.glob('data/*.*')), ('tools', glob.glob('tools/*.*'))]
OPTIONS = {'argv_emulation': False,
    'iconfile': 'config/icon.icns'}

setup(
    app=APP,
    name='Colin\'s Venmo Tools',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
